export const ACTION_TYPES = {
    DELETE: 'DELETE',
    EDIT: 'EDIT',
    DRAFT: 'DRAFT',
    CLOSE: 'CLOSE',
    REOPEN:'REOPEN',
    REJECT: 'REJECT',
    ARCHIVE: 'ARCHIVE',
    REOPEN:'REOPEN'
  };