export const JOB_PROFILES = {
  UIUX: "UI UX",
  MOTION_DESIGNER: "Motion Designer",
  "3D_DESIGNER": "3D Designer",
  CREATIVE_DIRECTOR: "Creative Director",
  PRODUCT_DESIGNER: "Product Designer",
  BRAND_DESIGNER: "Brand Designer",
  VIDEO_EDITOR: "Video Editor",
  GRAPHIC_DESIGNER: "Graphic Designer",
  DESIGNER: "Designer",
  // SOCIAL_MEDIA_ASSETS_DESIGNER: "Social Media Assets Designer",
};

export const jobStagesStatuses = {
  [JOB_PROFILES.UIUX]: [
    {
      name: "Portfolio",
      requiresCall: false,
      statuses: [
        "Not Assigned",
        "Under Review",
        "Reviewed",
        "Cleared",
        "Rejected",
      ],
    },
    {
      name: "Screening",
      requiresCall: true,
      scoreConfig : {
        Attitude : 5,
        Communication : 5,
        Budget : 5,
        Narrative : 5,
        'UI/UX' : 5,
        HTML : 5,
      },
      statuses: [
        "Pending",
        "Call Scheduled",
        "Under Review",
        "Reviewed",
        "Cleared",
        "No Show",
        "Rejected",
      ],
    },
    {
      name: "Design Task",
      requiresCall: true,
      statuses: [
        "Pending",
        "Not Assigned",
        "Sent",
        "Under Review",
        "Reviewed",
        "Cleared",
        "Rejected",
        "Not Submitted",
      ],
    },
    {
      name: "Round 1",
      requiresCall: true,
      statuses: [
        "Pending",
        "Call Scheduled",
        "Reviewed",
        "Cleared",
        "No Show",
        "Rejected",
      ],
    },
    {
      name: "Round 2",
      requiresCall: true,
      statuses: [
        "Pending",
        "Call Scheduled",
        "Reviewed",
        "Cleared",
        "No Show",
        "Rejected",
      ],
    },
    {
      name: "Hired",
      requiresCall: true,
      statuses: ["Under Review", "Offer Sent", "Accepted", "Rejected"],
    },
  ],
  [JOB_PROFILES.MOTION_DESIGNER]: [
    {
      name: "Portfolio",
      requiresCall: false,
      statuses: [
        "Not Assigned",
        "Under Review",
        "Reviewed",
        "Cleared",
        "Rejected",
      ],
    },
    {
      name: "Screening",
      requiresCall: true,
      scoreConfig : {
        Attitude : 5,
        Communication : 5,
        Budget : 5,
        Animation : 5,
        Narrative : 5,
        Tooling : 5,
      },
      statuses: [
        "Pending",
        "Call Scheduled",
        "Under Review",
        "Reviewed",
        "Cleared",
        "No Show",
        "Rejected",
      ],
    },
    {
      name: "Design Task",
      requiresCall: true,
      statuses: [
        "Pending",
        "Not Assigned",
        "Sent",
        "Under Review",
        "Reviewed",
        "Cleared",
        "Rejected",
        "Not Submitted",
      ],
    },
    {
      name: "Round 1",
      requiresCall: true,
      statuses: [
        "Pending",
        "Call Scheduled",
        "Reviewed",
        "Cleared",
        "No Show",
        "Rejected",
      ],
    },
    {
      name: "Round 2",
      requiresCall: true,
      statuses: [
        "Pending",
        "Call Scheduled",
        "Reviewed",
        "Cleared",
        "No Show",
        "Rejected",
      ],
    },
    {
      name: "Hired",
      requiresCall: true,
      statuses: ["Under Review", "Offer Sent", "Accepted", "Rejected"],
    },
  ],
  [JOB_PROFILES["3D_DESIGNER"]]: [
    {
      name: "Portfolio",
      requiresCall: false,
      statuses: [
        "Not Assigned",
        "Under Review",
        "Reviewed",
        "Cleared",
        "Rejected",
      ],
    },
    {
      name: "Screening",
      requiresCall: true,
      scoreConfig : {
        Attitude : 5,
        Communication : 5,
        Budget : 5,
        Modelling : 5,
        Rendering : 5,
        Creativity : 5,
      },
      statuses: [
        "Pending",
        "Call Scheduled",
        "Under Review",
        "Reviewed",
        "Cleared",
        "No Show",
        "Rejected",
      ],
    },
    {
      name: "Design Task",
      requiresCall: true,
      statuses: [
        "Pending",
        "Not Assigned",
        "Sent",
        "Under Review",
        "Reviewed",
        "Cleared",
        "Rejected",
        "Not Submitted",
      ],
    },
    {
      name: "Round 1",
      requiresCall: true,
      statuses: [
        "Pending",
        "Call Scheduled",
        "Reviewed",
        "Cleared",
        "No Show",
        "Rejected",
      ],
    },
    {
      name: "Round 2",
      requiresCall: true,
      statuses: [
        "Pending",
        "Call Scheduled",
        "Reviewed",
        "Cleared",
        "No Show",
        "Rejected",
      ],
    },
    {
      name: "Hired",
      requiresCall: true,
      statuses: ["Under Review", "Offer Sent", "Accepted", "Rejected"],
    },
  ],
  [JOB_PROFILES.CREATIVE_DIRECTOR]: [
    {
      name: "Portfolio",
      requiresCall: false,
      statuses: [
        "Not Assigned",
        "Under Review",
        "Reviewed",
        "Cleared",
        "Rejected",
      ],
    },
    {
      name: "Screening",
      requiresCall: true,
      scoreConfig : {
        Attitude : 5,
        Communication : 5,
        Budget : 5,
        Vision : 5,
        Leadership : 5,
        Strategy : 5,
      },
      statuses: [
        "Pending",
        "Call Scheduled",
        "Under Review",
        "Reviewed",
        "Cleared",
        "No Show",
        "Rejected",
      ],
    },
    {
      name: "Design Task",
      requiresCall: true,
      statuses: [
        "Pending",
        "Not Assigned",
        "Sent",
        "Under Review",
        "Reviewed",
        "Cleared",
        "Rejected",
        "Not Submitted",
      ],
    },
    {
      name: "Round 1",
      requiresCall: true,
      statuses: [
        "Pending",
        "Call Scheduled",
        "Reviewed",
        "Cleared",
        "No Show",
        "Rejected",
      ],
    },
    {
      name: "Round 2",
      requiresCall: true,
      statuses: [
        "Pending",
        "Call Scheduled",
        "Reviewed",
        "Cleared",
        "No Show",
        "Rejected",
      ],
    },
    {
      name: "Hired",
      requiresCall: true,
      statuses: ["Under Review", "Offer Sent", "Accepted", "Rejected"],
    },
  ],
  [JOB_PROFILES.PRODUCT_DESIGNER]: [
    {
      name: "Portfolio",
      requiresCall: false,
      statuses: [
        "Not Assigned",
        "Under Review",
        "Reviewed",
        "Cleared",
        "Rejected",
      ],
    },
    {
      name: "Screening",
      requiresCall: true,
      scoreConfig : {
        Attitude : 5,
        Communication : 5,
        Budget : 5,
        'Core Thinking' : 5,
        UX : 5,
        Consistency : 5,
      },
      statuses: [
        "Pending",
        "Call Scheduled",
        "Under Review",
        "Reviewed",
        "Cleared",
        "No Show",
        "Rejected",
      ],
    },
    {
      name: "Design Task",
      requiresCall: true,
      statuses: [
        "Pending",
        "Not Assigned",
        "Sent",
        "Under Review",
        "Reviewed",
        "Cleared",
        "Rejected",
        "Not Submitted",
      ],
    },
    {
      name: "Round 1",
      requiresCall: true,
      statuses: [
        "Pending",
        "Call Scheduled",
        "Reviewed",
        "Cleared",
        "No Show",
        "Rejected",
      ],
    },
    {
      name: "Round 2",
      requiresCall: true,
      statuses: [
        "Pending",
        "Call Scheduled",
        "Reviewed",
        "Cleared",
        "No Show",
        "Rejected",
      ],
    },
    {
      name: "Hired",
      requiresCall: true,
      statuses: ["Under Review", "Offer Sent", "Accepted", "Rejected"],
    },
  ],
  [JOB_PROFILES.BRAND_DESIGNER]: [
    {
      name: "Portfolio",
      requiresCall: false,
      statuses: [
        "Not Assigned",
        "Under Review",
        "Reviewed",
        "Cleared",
        "Rejected",
      ],
    },
    {
      name: "Screening",
      requiresCall: true,
        scoreConfig : {
        Attitude : 5,
        Communication : 5,
        Budget : 5,
        Identity : 5,
        Consistency : 5,
        Narrative : 5,
      },
      statuses: [
        "Pending",
        "Call Scheduled",
        "Under Review",
        "Reviewed",
        "Cleared",
        "No Show",
        "Rejected",
      ],
    },
    {
      name: "Design Task",
      requiresCall: true,
      statuses: [
        "Pending",
        "Not Assigned",
        "Sent",
        "Under Review",
        "Reviewed",
        "Cleared",
        "Rejected",
        "Not Submitted",
      ],
    },
    {
      name: "Round 1",
      requiresCall: true,
      statuses: [
        "Pending",
        "Call Scheduled",
        "Reviewed",
        "Cleared",
        "No Show",
        "Rejected",
      ],
    },
    {
      name: "Round 2",
      requiresCall: true,
      statuses: [
        "Pending",
        "Call Scheduled",
        "Reviewed",
        "Cleared",
        "No Show",
        "Rejected",
      ],
    },
    {
      name: "Hired",
      requiresCall: true,
      statuses: ["Under Review", "Offer Sent", "Accepted", "Rejected"],
    },
  ],
  [JOB_PROFILES.VIDEO_EDITOR]: [
    {
      name: "Portfolio",
      requiresCall: false,
      statuses: [
        "Not Assigned",
        "Under Review",
        "Reviewed",
        "Cleared",
        "Rejected",
      ],
    },
    {
      name: "Screening",
      requiresCall: true,
      scoreConfig : {
        Attitude : 5,
        Communication : 5,
        Budget : 5,
        Editing : 5,
        Timing : 5,
        Composition : 5,
      },
      statuses: [
        "Pending",
        "Call Scheduled",
        "Under Review",
        "Reviewed",
        "Cleared",
        "No Show",
        "Rejected",
      ],
    },
    {
      name: "Design Task",
      requiresCall: true,
      statuses: [
        "Pending",
        "Not Assigned",
        "Sent",
        "Under Review",
        "Reviewed",
        "Cleared",
        "Rejected",
        "Not Submitted",
      ],
    },
    {
      name: "Round 1",
      requiresCall: true,
      statuses: [
        "Pending",
        "Call Scheduled",
        "Reviewed",
        "Cleared",
        "No Show",
        "Rejected",
      ],
    },
    {
      name: "Round 2",
      requiresCall: true,
      statuses: [
        "Pending",
        "Call Scheduled",
        "Reviewed",
        "Cleared",
        "No Show",
        "Rejected",
      ],
    },
    {
      name: "Hired",
      requiresCall: true,
      statuses: ["Under Review", "Offer Sent", "Accepted", "Rejected"],
    },
  ],
  [JOB_PROFILES.GRAPHIC_DESIGNER]: [
    {
      name: "Portfolio",
      requiresCall: false,
      statuses: [
        "Not Assigned",
        "Under Review",
        "Reviewed",
        "Cleared",
        "Rejected",
      ],
    },
    {
      name: "Screening",
      requiresCall: true,
      scoreConfig : {
        Attitude : 5,
        Communication : 5,
        Budget : 5,
        Aesthetics : 5,
        Creativity : 5,
        Layout : 5,
      },
      statuses: [
        "Pending",
        "Call Scheduled",
        "Under Review",
        "Reviewed",
        "Cleared",
        "No Show",
        "Rejected",
      ],
    },
    {
      name: "Design Task",
      requiresCall: true,
      statuses: [
        "Pending",
        "Not Assigned",
        "Sent",
        "Under Review",
        "Reviewed",
        "Cleared",
        "Rejected",
        "Not Submitted",
      ],
    },
    {
      name: "Round 1",
      requiresCall: true,
      statuses: [
        "Pending",
        "Call Scheduled",
        "Reviewed",
        "Cleared",
        "No Show",
        "Rejected",
      ],
    },
    {
      name: "Round 2",
      requiresCall: true,
      statuses: [
        "Pending",
        "Call Scheduled",
        "Reviewed",
        "Cleared",
        "No Show",
        "Rejected",
      ],
    },
    {
      name: "Hired",
      requiresCall: true,
      statuses: ["Under Review", "Offer Sent", "Accepted", "Rejected"],
    },
  ],
  [JOB_PROFILES.DESIGNER]: [
    {
      name: "Portfolio",
      requiresCall: false,
      statuses: [
        "Not Assigned",
        "Under Review",
        "Reviewed",
        "Cleared",
        "Rejected",
      ],
    },
    {
      name: "Screening",
      requiresCall: true,
      scoreConfig : {
        Attitude : 5,
        Communication : 5,
        Budget : 5,
        Aesthetics : 5,
        Creativity : 5,
        Layout : 5,
      },
      statuses: [
        "Pending",
        "Call Scheduled",
        "Under Review",
        "Reviewed",
        "Cleared",
        "No Show",
        "Rejected",
      ],
    },
    {
      name: "Design Task",
      requiresCall: true,
      statuses: [
        "Pending",
        "Not Assigned",
        "Sent",
        "Under Review",
        "Reviewed",
        "Cleared",
        "Rejected",
        "Not Submitted",
      ],
    },
    {
      name: "Round 1",
      requiresCall: true,
      statuses: [
        "Pending",
        "Call Scheduled",
        "Reviewed",
        "Cleared",
        "No Show",
        "Rejected",
      ],
    },
    {
      name: "Round 2",
      requiresCall: true,
      statuses: [
        "Pending",
        "Call Scheduled",
        "Reviewed",
        "Cleared",
        "No Show",
        "Rejected",
      ],
    },
    {
      name: "Hired",
      requiresCall: true,
      statuses: ["Under Review", "Offer Sent", "Accepted", "Rejected"],
    },
  ],
  // [JOB_PROFILES.SOCIAL_MEDIA_ASSETS_DESIGNER]: [
  //   {
  //     name: "Portfolio",
  //     requiresCall: false,
  //     statuses: [
  //       "Not Assigned",
  //       "Under Review",
  //       "Reviewed",
  //       "Cleared",
  //       "Rejected",
  //     ],
  //   },
  //   {
  //     name: "Screening",
  //     requiresCall: true,
  //     scoreConfig : {
  //       Attitude : 5,
  //       Communication : 5,
  //       Budget : 5,
  //       Engagement : 5,
  //       Adaptability : 5,
  //       Branding : 5,
  //     },
  //     statuses: [
  //       "Pending",
  //       "Call Scheduled",
  //       "Under Review",
  //       "Reviewed",
  //       "Cleared",
  //       "No Show",
  //       "Rejected",
  //     ],
  //   },
  //   {
  //     name: "Design Task",
  //     requiresCall: true,
  //     statuses: [
  //       "Pending",
  //       "Not Assigned",
  //       "Sent",
  //       "Under Review",
  //       "Reviewed",
  //       "Cleared",
  //       "Rejected",
  //       "Not Submitted",
  //     ],
  //   },
  //   {
  //     name: "Round 1",
  //     requiresCall: true,
  //     statuses: [
  //       "Pending",
  //       "Call Scheduled",
  //       "Reviewed",
  //       "Cleared",
  //       "No Show",
  //       "Rejected",
  //     ],
  //   },
  //   {
  //     name: "Round 2",
  //     requiresCall: true,
  //     statuses: [
  //       "Pending",
  //       "Call Scheduled",
  //       "Reviewed",
  //       "Cleared",
  //       "No Show",
  //       "Rejected",
  //     ],
  //   },
  //   {
  //     name: "Hired",
  //     requiresCall: true,
  //     statuses: ["Under Review", "Offer Sent", "Accepted", "Rejected"],
  //   },
  // ],
};
